import NavBar from "@/components/views/Layout/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import { Sora } from "next/font/google";
import Wrapper from "@/components/shared/Wrapper/page";
import Footer from "@/components/views/Layout/Footer";
import SubFooter from "@/components/views/Layout/SubFooter";

const inter = Sora({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <NavBar />
          {children}
          <Footer />
          <SubFooter />
        </Wrapper>
      </body>
    </html>
  );
}
